FROM golang:1.21-bookworm

# -----------------------------------------------------------------------------
# Install dev-dependencies
# -----------------------------------------------------------------------------

WORKDIR /home/vscode
RUN apt-get update && \
apt-get install curl -y
